jobs:
  deploy_to_tomcat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt

      - name: Download Artifact from GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o vprofile-v2.war -L "https://github.com/your_github_userythrinathareddy/hprofile/home/runner/work/hprofile/hprofile/target/vprofile-v2.war"
        # Update with your GitHub username, repository name, and the correct release tag

      - name: Deploy to Tomcat
        run: |
          curl -u admin:3nath@Reddy --upload-file vprofile-v2.war http://your_tomcat_host:8080//u01/tomcat/webapps/manager?path=/vprofile-v2&update=true
        # Update with your Tomcat username, password, host, and the correct deployment path

          # Add a step to upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: java-artifact
          path: target/*.jar

      # Publish the Maven package to GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GIT_TOKEN}}" >> $HOME/.npmrc
          mvn deploy -DskipTests=true --settings settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Publish to GitHub Packages
        run: mvn deploy -DskipTests=true --settings settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: "Publish to GitHub Packages"
    needs: [build]
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ythrinathareddy' # && github.token != ''
    steps:
      - name: Upload
        uses: actions/download-artifact@v4
        with:
          name: vprofile
          path: /home/runner/work/hprofile/hprofile/target
      - name: Publish to GitHub Packages
        run: mvn deploy --settings .m2/settings.xml
        mvn deploy -X --global-settings /path/to/settings.xml

        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITUSER_TOKEN }}

pom 
<distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/ythrinathareddy/hprofile</url>
        </repository>
    </distributionManagement>
    

         