name: action test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: code checkout
        uses: actions/checkout@v4

      - name: mavan test
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: list the current directory
        run: ls -a
              
      - name: Print Contents of the Target Folder
        run: |
          cd target
          pwd
          ls -a
    
     # Use the variable in the upload artifact step
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vprofile
          path: /home/runner/work/hprofile/hprofile/target
      
      
      