name: action test
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: code checkout
        uses: actions/checkout@v4

      - name: mavan test
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: list the current directory
        run: ls -action
              
      - name: what is in the target folder
        run: |
          cd target
          pwd
          ls -a
      - uses: actions/upload-artifact@v4
        with:
        name: my-artifact
        path: path/to/artifact/ # or path/to/artifact

      
      
      